# The module 10 by analytics : Exceptions in the python

## lesson 2 : basic Numpy

In [1]:
import numpy as np

In [5]:
#create array with one-diminsion
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [12]:
# check type variable a
type(a)
# it is N-dimensional array, ok

numpy.ndarray

In [14]:
# create array with two-dimension
b = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
# get one list
b[0]

array([1, 2, 3])

In [18]:
# create tree-dimension
# it will be the view of the table

c = np.array([
    [[1, 2, 3],
     [4, 5, 6]],
    
    [[7, 8, 9],
     [10, 11, 12]]
])
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
c[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
c[0][1][1]

5

In [26]:
# create array with differect count elements in lists
d = np.array([[1, 2, 3], [4, 5, ]])
d
# get Warning but it created

/tmp/ipykernel_47012/707311034.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  d = np.array([[1, 2, 3], [4, 5, ]])


array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [27]:
d

array([list([1, 2, 3]), list([4, 5])], dtype=object)

## lesson 3 by operation with NDarray 

In [28]:
turnout = np.array([0.53, 0.5, 0.12])

In [29]:
turnout * 100

array([53., 50., 12.])

In [33]:
g = (np.array([1, 2, 3]) + np.array([67, 5, 89])) ** 3
g

array([314432,    343, 778688])

In [36]:
type(g[0])

numpy.int64

In [37]:
g[0] / 0

/tmp/ipykernel_47012/1662875502.py:1: RuntimeWarning: divide by zero encountered in long_scalars
  g[0] / 0


inf

In [45]:
g[5]

IndexError: index 5 is out of bounds for axis 0 with size 3

In [47]:
weight = np.array([[1, 2, 3],
                   [4, 5, 6]])

In [48]:
weight[0, 1]

2

In [49]:
l1 = [[1, 2, 3], [4, 5, 6]]

In [53]:
l1[::-1]

[[4, 5, 6], [1, 2, 3]]