# The module 10 by analytics : Numpy(1)

## lesson 2 : basic Numpy

In [1]:
import numpy as np

In [2]:
#create array with one-diminsion
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
# check type variable a
type(a)
# it is N-dimensional array, ok

numpy.ndarray

In [4]:
# create array with two-dimension
b = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# get one list
b[0]

array([1, 2, 3])

In [6]:
# create tree-dimension
# it will be the view of the table

c = np.array([
    [[1, 2, 3],
     [4, 5, 6]],
    
    [[7, 8, 9],
     [10, 11, 12]]
])
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [7]:
c[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
c[0][1][1]

5

In [9]:
# create array with differect count elements in lists
d = np.array([[1, 2, 3], [4, 5, ]])
d
# get Warning but it created

/tmp/ipykernel_25212/707311034.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  d = np.array([[1, 2, 3], [4, 5, ]])


array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [10]:
d

array([list([1, 2, 3]), list([4, 5])], dtype=object)

## lesson 3 by operation with NDarray 

In [11]:
turnout = np.array([0.53, 0.5, 0.12])

In [12]:
turnout * 100

array([53., 50., 12.])

In [13]:
g = (np.array([1, 2, 3]) + np.array([67, 5, 89])) ** 3
g

array([314432,    343, 778688])

In [14]:
type(g[0])

numpy.int64

In [15]:
g[0] / 0

/tmp/ipykernel_25212/1662875502.py:1: RuntimeWarning: divide by zero encountered in long_scalars
  g[0] / 0


inf

In [16]:
g[5]

IndexError: index 5 is out of bounds for axis 0 with size 3

In [ ]:
weight = np.array([[1, 2, 3],
                   [4, 5, 6]])

In [ ]:
weight[0, 1]

In [ ]:
l1 = [[1, 2, 3], [4, 5, 6]]

In [ ]:
l1[::-1]

In [ ]:
a = (3, 2, 6)

In [ ]:
3 in a

In [19]:
np.arange(2, 10 , 2)

array([2, 4, 6, 8])

In [20]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
price = np.arange(100, 500, 25)
price

array([100, 125, 150, 175, 200, 225, 250, 275, 300, 325, 350, 375, 400,
       425, 450, 475])

In [51]:
sort_price = (200 < price) & (price < 400)
sort_price

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False])

In [53]:
sort_price.sum()

7

In [55]:
# sort out array with other conditions and get values which will be equal to our conditions
price[(price > 200) & (price < 400)]
# get down values where every value be equal to conditions

array([225, 250, 275, 300, 325, 350, 375])