# The module 11 by analytics : Numpy(2)

## lesson 1 : change dimension in Ndarray

In [1]:
import numpy as np

In [4]:
a = np.arange(2, 30, 2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [6]:
a.ndim

1

In [7]:
a.shape

(14,)

In [16]:
X = a.reshape(7, 2)
X
# used to the fuction by reshape for change the form of array

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20],
       [22, 24],
       [26, 28]])

In [18]:
X_T = X.transpose() 
X_T

# doing trasposition, or with help to the X.T

array([[ 2,  6, 10, 14, 18, 22, 26],
       [ 4,  8, 12, 16, 20, 24, 28]])

In [22]:
np.array_equal(X.T, X.transpose())

True

In [23]:
#collapse to one row
X_T.ravel()

array([ 2,  6, 10, 14, 18, 22, 26,  4,  8, 12, 16, 20, 24, 28])